name: "Eswater"
version: "1.0.0"
slug: "eswater"
description: "Monitor Essex and Suffolk Water Smart Meter"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
hassio_api: true
homeassistant_api: true
options:
  eswater_username: ""
  eswater_password: ""
  update_interval: 3600
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  log_level: "info"
schema:
  eswater_username: str
  eswater_password: password
  update_interval: int?
  mqtt_host: str?
  mqtt_port: port?
  mqtt_user: str?
  mqtt_password: password?
  log_level: list(debug|info|warning|error)?
